name: Globant DE Challenge Web Deploy

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main 
      
  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Dependencies
        working-directory: ./employees_site
        run: flutter pub get
      - name: 'Create env file'
        run: |
          touch ./employees_site/.env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> ./employees_site/.env
          cat ./employees_site/.env
      - name: Build
        working-directory: ./employees_site
        run: flutter build web
      - name: Upload Artifacts
        uses: actions/upload-artifact@master
        with:
          name: flutter-build
          path: ./employees_site/build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@master
        with:
          name: flutter-build
          path: build/web
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Deploy
        uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_GLOBANT_CHALLENGE_WEB }}'
          channelId: live
          projectId: globant-challenge-web
