name: Globant DE Challenge Web Deploy

on:
  pull_request:
    branches:
      - main 

  workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Install Dependencies
        working-directory: ./employees_site
        run: flutter pub get
      - name: 'Create env file'
        run: |
          touch .env
          echo OPENAI_API_KEY=${{ secrets.OPENAI_API_KEY }} >> .env
          cat .env
      - name: Build
        working-directory: ./employees_site
        run: flutter build web
      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: flutter-build
          path: build/web

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: flutter-build
          path: build/web
      - name: Setup NodeJS
        uses: actions/setup-node@v2
        with:
          node-version: "16"
      - name: Install Firebase CLI
        run: npm install -g firebase-tools
      - name: Deploy
        run: firebase deploy